# Generated by Django 5.0.6 on 2024-10-14 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Biodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('home_address', models.CharField(max_length=100)),
                ('religion', models.CharField(choices=[('christian', 'Christian'), ('muslim', 'Muslim'), ('other', 'Other')], max_length=10)),
                ('tribe', models.CharField(choices=[('igbo', 'Igbo'), ('hausa', 'Hausa'), ('yoruba', 'Yoruba'), ('other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Internal_Medicine_Clerking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField()),
                ('past_medical_history', models.TextField()),
                ('family_history', models.TextField()),
                ('social_history', models.TextField()),
                ('physical_examination', models.TextField()),
                ('assessment', models.TextField()),
                ('patient_biodata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clerking_pad.patient_biodata')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery_Clerking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField()),
                ('past_medical_history', models.TextField()),
                ('family_history', models.TextField()),
                ('social_history', models.TextField()),
                ('patient_biodata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clerking_pad.patient_biodata')),
            ],
        ),
    ]
