# Generated by Django 5.0.6 on 2024-10-19 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerking_pad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgery_clerking',
            name='patient_biodata',
        ),
        migrations.CreateModel(
            name='Clerking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('home_address', models.CharField(max_length=100)),
                ('religion', models.CharField(choices=[('christian', 'Christian'), ('muslim', 'Muslim'), ('other', 'Other')], max_length=10)),
                ('tribe', models.CharField(choices=[('igbo', 'Igbo'), ('hausa', 'Hausa'), ('yoruba', 'Yoruba'), ('other', 'Other')], max_length=10)),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField()),
                ('past_medical_history', models.TextField()),
                ('past_surgical_history', models.TextField()),
                ('family_history', models.TextField()),
                ('social_history', models.TextField()),
                ('general_examination', models.TextField()),
                ('chest_examination', models.TextField(blank=True, null=True)),
                ('cardiovascular_examination', models.TextField(blank=True, null=True)),
                ('abdominal_examination', models.TextField(blank=True, null=True)),
                ('neurological_examination', models.TextField(blank=True, null=True)),
                ('musculoskeletal_examination', models.TextField(blank=True, null=True)),
                ('assessment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Internal_Medicine_Clerking',
        ),
        migrations.DeleteModel(
            name='Patient_Biodata',
        ),
        migrations.DeleteModel(
            name='Surgery_Clerking',
        ),
    ]
